sudo: required
language: generic
services:
  - docker

env:
  global:
    - OMF_REPO_URI="https://github.com/$TRAVIS_REPO_SLUG"
    - OMF_REPO_BRANCH="$TRAVIS_BRANCH"

before_install:
  - source tools/travis-github-pr-integration.sh

before_script:
  - docker build --build-arg OMF_REPO_BRANCH=$OMF_REPO_BRANCH --build-arg OMF_REPO_URI=$OMF_REPO_URI -t oh-my-fish . < Dockerfile
  - docker run -t oh-my-fish /usr/bin/fish -c "export; tree -h"

script:
  - docker run -t oh-my-fish /usr/bin/fish "tests/run.fish"
  - docker run -t oh-my-fish /usr/bin/fish -c "cd pkg/fish-spec; fish-spec"
  - docker run -t oh-my-fish /usr/bin/fish -c "cd pkg/omf; fish-spec"
  - docker run -t oh-my-fish /usr/bin/fish "tests/test-generate-themes-doc.fish"

after_failure:
  - docker ps -a

notifications:
  email:
    on_success: never
    on_failure: change
  slack:
    secure: fHR34H901zaBpUdm9BECQfocnPki8HdigH9CQxopvJ6Rm0WCLzCst4zPESAlO/Jb1t6OYtU6Goqmdq3yqzo8+moCrygrpMUtzIel/TDhkLzC2SIlmMdnw2/Xdwzisd/8QBVwu9ns8xJ2C4eegolNazNsc1Ow/wULaLwA7vUJrfcSmvYBepfe3MPSX/KLU3BBRhiTr3RhuzV+D1qQcSrAiWGVr4zWUiRAar6WD1D4athZO9OX33upBYpraGEa3sRWrUJjVv7KWMH566Y2MSAtd0NBgsF9dn3S5nKTXtfyGXt2gkykZ9Ag1B7B9AR9BHpn5UcvDdn7FZpEREfrllkDU8iG67RD7owyRl/T5jyWQecU2Q9Rlco5esEpbkY7sXmzwj2RVBGzsaVjxajZ+C7Ns2ogMcP8o+xqfcUASXjlJM2kJQRSenwx82Vq6uQ0vbhgKWBTQE1qsEkLDCthUxQ9eJ0/exoBp95wrZinilmEyps00oqmS40HEhB+JmuN2sGVWhpSczVDvVmdV+XSewLqfRnWtr2yhL8dR1sfVm2lJh3Dzik4BFUASByeBJnViU4dDilLlb4S3Dwk0XZh9HGwLs9ujNA3PT23uoRu4VRBQkIwXZE8v/qvf4/7w8IowofzezYcjwxkaqu1hNgTKNOkbgopV9RdwrUxy4f53S0l2jY=
